TarteelAI/quranic-universal-library

app/assets/stylesheets/landing_page/_tool_cards.scss, app/helpers/landing_helper.rb, app/models/downloadable_resource.rb, app/models/resource_content.rb, app/views/landing/_overview.html.erb, app/views/resources/_quran_script_preview.html.erb, lib/exporter/base_exporter.rb, lib/exporter/downloadable_resources.rb, lib/exporter/export_ayah_theme.rb, lib/exporter/export_quranic_morphology.rb
=> Export morphology

lib/exporter/base_exporter.rb, lib/exporter/downloadable_resources.rb, lib/exporter/export_ayah_recitation.rb, lib/exporter/export_translation.rb, lib/exporter/export_word_transliteration.rb
- Added batch process, this will increase export time but will reduce the memory consumption 
- Fixed translations chunk export
=> Batch processing and fixed text chunks export

lib/utils/db_backup.rb
This PR add the support to export database dumps in binary format
=> Optionally export the db dumps in binary format

Gemfile, Gemfile.lock
Bumps nokogiri from 1.14.3 to 1.16.5.
=> upgrade nokogiri

app/assets/stylesheets/components/common.scss, app/assets/stylesheets/landing_page/_hero.scss, app/helpers/arabic_transliterations_helper.rb, app/views/landing/_hero.html.erb, app/views/landing/home.html.erb
- Fixes sort icon alignment
- Tweaks landing page hero
=> [TA-1365] UI Polish - Part 3

app/assets/stylesheets/components/_resources.scss, app/views/resources/_featured_cards.html.erb, app/views/resources/_resources_list.html.erb, app/views/resources/show.html.erb
=> [TA-1365] Fix card grid

app/assets/stylesheets/components/_resources.scss, app/assets/stylesheets/landing_page/_tool_cards.scss, app/views/community/tools.html.erb, app/views/landing/_resources.html.erb, app/views/landing/_tools.html.erb, app/views/resources/_featured_cards.html.erb, app/views/resources/_resources_list.html.erb
- Make cards consistent across site
=> [TA-1365] UI Polish - Part 6

app/admin/user.rb, app/assets/stylesheets/active_admin.scss, app/assets/stylesheets/landing_page/index.scss, app/javascript/controllers/for_admin.js, app/javascript/controllers/index.js, app/javascript/controllers/toggle_password_controller.js, app/models/contact_message.rb, app/models/downloadable_file.rb, app/models/draft/tafsir.rb, app/models/draft/translation.rb, app/models/morphology/matching_verse.rb, app/models/morphology/phrase.rb, app/models/morphology/phrase_verse.rb, app/models/raw_data/resource.rb, app/models/user.rb, app/models/wbw_text.rb, app/views/devise/registrations/_form.html.erb, app/views/devise/sessions/_form.html.erb, app/views/layouts/devise.html.erb, config/initializers/active_admin.rb, db/migrate/20240219201808_add_digital_khat_text.rb, db/schema.rb, db/seed.rb
Add toggle password on signup and login page
=> Add toggle password

app/assets/stylesheets/components/_credit.scss, app/assets/stylesheets/landing_page/_header.scss, app/views/community/credits.html.erb, app/views/landing/_footer.html.erb, app/views/landing/_header.html.erb, app/views/layouts/application.html.erb
=> Credits Page: Make font size consistent + adjust layout for nicer line width

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/landing/_footer.html.erb, app/views/landing/_header.html.erb, app/views/learning_activities/show.html.erb, app/views/resources/show.html.erb, app/views/shared/not_found.html.erb, db/migrate/20240808134403_rename_topic_children_column.rb, db/schema.rb
- Render 404 page for unknown request format
- Fixed login popup
=> Fix login popup when visitor try to download resource

app/admin/downloads/downloadable_resource.rb, app/jobs/async_resource_action_job.rb, app/models/contact_message.rb, app/models/downloadable_resource.rb, app/models/draft/tafsir.rb, app/models/draft/translation.rb, app/models/morphology/matching_verse.rb, app/models/morphology/phrase.rb, app/models/morphology/phrase_verse.rb, app/models/raw_data/resource.rb, app/models/resource_content.rb, app/models/user.rb, app/models/wbw_text.rb, db/migrate/20240824181741_add_files_count_to_downloadable_resource.rb, db/schema.rb, lib/exporter/downloadable_resources.rb
- Allow admins to refresh the exported files via admin section
- Added exported files count to downloadable resources to quickly fine which resource has isn't exported yet
=> Refresh exported files

app/admin/quran/word.rb, app/models/application_record.rb, app/models/quran_api_record.rb, app/models/resource_content.rb, app/models/topic.rb, app/models/word.rb, db/migrate/20240826103347_add_word_metadata.rb, db/schema.rb
This PR add `meta_data` json fields to words table, we'll use this to persist metadata related to word.
=> Add word meta data

app/assets/stylesheets/active_admin.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/pdf.scss, app/assets/stylesheets/shared/font_faces.scss, app/assets/stylesheets/shared/indopak_font_faces.scss, app/assets/stylesheets/shared/surah_names.scss
This PR add the cdn host to surah name font URL.
=> Fix surah name font face

app/admin/dashboard.rb, app/admin/quran/hizb.rb, app/admin/quran/juz.rb, app/admin/quran/manzil.rb, app/admin/quran/mushaf_line_alignment.rb, app/admin/quran/mushaf_page_preview.rb, app/admin/quran/mushaf_word.rb, app/admin/quran/rub_el_hizb.rb, app/admin/quran/ruku.rb, app/admin/tools/data_integrity_check.rb, app/admin/topic.rb, app/assets/stylesheets/components/wraper.scss, app/controllers/application_controller.rb, app/helpers/mushaf_page_helper.rb, app/models/concerns/has_verse_mapping.rb, app/models/hizb.rb, app/models/juz.rb, app/models/manzil.rb, app/models/mushaf.rb, app/models/rub_el_hizb.rb, app/models/ruku.rb, app/models/tools/data_integrity_checks.rb, app/models/topic.rb, app/views/admin/_data_integrity_check_filters.html.erb, app/views/community/_char_font_options.html.erb, app/views/community/_char_info_form.html.erb, app/views/community/_chars_table.html.erb, app/views/community/chars_info.html.erb, app/views/landing/_header.html.erb, lib/export_mushaf_layout.rb
- Added ayah filters for Topics
- Fixed "chapter" filter for juz, hizb, manzil etc 
- Improved chars tool
=> Improved the char tools and filters in admin

app/admin/quran/tajweed_word.rb, app/assets/stylesheets/components/_tajweed_rules.scss, app/assets/stylesheets/components/wraper.scss, app/assets/stylesheets/shared/tajweed_color_new.scss, app/controllers/tajweed_words_controller.rb, app/helpers/tajweed_helper.rb, app/javascript/controllers/tajweed_highlight_controller.js, app/models/tajweed_word.rb, app/models/word.rb, app/views/tajweed_words/_letter_row.html.erb, app/views/tajweed_words/_word_preview.html.erb, app/views/tajweed_words/index.html.erb, app/views/tajweed_words/rule_doc.html.erb, app/views/tajweed_words/show.html.erb, app/views/tajweed_words/update.turbo_stream.erb, app/views/tools/_header.html.erb, lib/quran_wa_hadit_parser.rb, lib/quran_word_finder.rb, lib/tajweed_annotation/letter_token.rb, lib/tajweed_annotation/service.rb, lib/tajweed_annotation/word_token.rb, lib/tajweed_rules.rb
This PR improves the tajweed tool:
- Added filters to find word with specific tajweed rule 
- Filter to search words with regexp 
- Added annotation script for 4 rules for now(laam_shamsiyah, slient, ham_wasl and izhar)
=> Add tajweed annotation

app/admin/audio/recitation.rb, app/models/draft/tafsir.rb, app/models/mushaf.rb, app/views/ayah_audio_files/index.html.erb, app/views/ayah_audio_files/segment_builder.html.erb, app/views/tafsir_proofreadings/index.html.erb
This PR fix ayah grouping if ayah range is changed in proposed changes.
=> Fix ayah grouping

app/admin/dashboard.rb, app/admin/quran/mushaf.rb, app/controllers/mushaf_layouts_controller.rb, app/jobs/export/mushaf_layout_export_job.rb, app/views/admin/_export_mushaf_layouts_db.html.erb, app/views/mushaf_layouts/_line_alignment.html.erb, app/views/mushaf_layouts/_page_line_alignment.html.erb, app/views/mushaf_layouts/_page_mapping.html.erb, app/views/mushaf_layouts/_page_mapping_with_pdf.html.erb, app/views/mushaf_layouts/_page_preview.html.erb, app/views/mushaf_layouts/_preview.html.erb, app/views/mushaf_layouts/_select_compare.html.erb, app/views/mushaf_layouts/edit.html.erb, app/views/mushaf_layouts/index.html.erb, app/views/mushaf_layouts/show.html.erb, app/views/shared/_mushaf_page.html.erb, app/views/surah_audio_files/index.html.erb, lib/export_mushaf_layout.rb
- Mushaf layout tool has a couple of actions, This PR will move those actions to dropdown. 
- Added compare layout action
=> Improved actions for mushaf layout

.gitignore, app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_pdf_preview.scss, app/assets/stylesheets/components/_tools_help.scss, app/helpers/tool_docs_helper.rb, app/javascript/controllers/index.js, app/javascript/controllers/lazy_load_controller.js, app/views/community/tool_help.html.erb, app/views/tools/header_alert/_mushaf_layout.html.erb, app/views/tools/header_alert/_mushaf_layouts.html.erb, app/views/tools/help/_mushaf_layout.html.erb, app/views/translation_proofreadings/index.html.erb
This PR improves to UI of tools help.
=> Improve UX of tools help

app/views/shared/_meta_tags.html.erb
Add extra `og:image` metadata:
- Image height + width
- Image alt
=> Add extra `og:image` metadata

app/controllers/landing_controller.rb, app/views/shared/_meta_tags.html.erb
Add meta description to homepage
=> Add meta description to homepage

app/views/shared/_meta_tags.html.erb
=> Fix favicon not showing

README.md
=> Add Stars to README

app/admin/quran/verse.rb, app/admin/quran/word.rb, app/models/tajweed_word.rb, app/models/verse.rb, app/models/word.rb, app/views/community/chars_info.html.erb, app/views/word_text_proofreadings/show.html.erb, db/migrate/20241007092406_add_dk_v1_script.rb, db/schema.rb
This PR add DK script for v1 script
=> Add digital khatt script for 1405H print

app/admin/audio/audio_recitation.rb, app/admin/audio/chapter_audio_file.rb, app/admin/audio/recitation.rb, app/admin/content/resource_content.rb, app/admin/database_backup.rb, app/admin/downloads/downloadable_resource.rb, app/admin/quran/word.rb, app/models/resource_content.rb, app/views/admin/_export_mushaf_layouts_db.html.erb, lib/export_mushaf_layout.rb
This PR adjust the mushaf export job to export DK v1 layout
=> Export DK v1 layout

app/views/shared/_meta_tags.html.erb
This updates our GTM ID to one more appropriate
=> Update GTM ID

app/controllers/arabic_transliterations_controller.rb, app/controllers/morphology_phrases_controller.rb, app/controllers/tafsir_proofreadings_controller.rb, app/controllers/tajweed_words_controller.rb, app/controllers/translation_proofreadings_controller.rb, app/controllers/wbw_texts_controller.rb, app/controllers/word_concordance_labels_controller.rb, app/controllers/word_text_proofreadings_controller.rb, app/controllers/word_translations_controller.rb, app/javascript/controllers/chapter_verses_filter_controller.js, app/javascript/controllers/index.js, app/views/arabic_transliterations/index.html.erb, app/views/ayah/_title.html.erb, app/views/ayah_audio_files/index.html.erb, app/views/community/_chars_table.html.erb, app/views/morphology_phrases/_phrase_list.html.erb, app/views/morphology_phrases/_proofread_list.html.erb, app/views/shared/_filters.html.erb, app/views/surah_audio_files/index.html.erb, app/views/surah_infos/index.html.erb, app/views/tafsir_proofreadings/index.html.erb, app/views/tajweed_words/index.html.erb, app/views/translation_proofreadings/index.html.erb, app/views/wbw_texts/index.html.erb, app/views/word_concordance_labels/index.html.erb, app/views/word_text_proofreadings/index.html.erb, app/views/word_translations/index.html.erb
=> Add dynamic ayah number filter based on selected surah

app/models/resource_content.rb, db/migrate/20241013215322_add_info_to_downloadable_file.rb, lib/exporter/downloadable_resources.rb, lib/exporter/export_font.rb
=> Export fonts

app/jobs/export/translation_json.rb
Export for Bridges` translations was missing Qirats footnotes.
=> Fix bridges translation export

.github/ISSUE_TEMPLATE/quran_script_issue_report.yml
=> Issue template for Quran script and font

app/controllers/community_controller.rb, app/helpers/landing_helper.rb, app/models/contact_message.rb, app/models/draft/tafsir.rb, app/models/draft/translation.rb, app/models/morphology/matching_verse.rb, app/models/morphology/phrase.rb, app/models/morphology/phrase_verse.rb, app/models/quran_api_record.rb, app/models/raw_data/resource.rb, app/models/tajweed_word.rb, app/models/user.rb, app/models/user_project.rb, app/models/verse.rb, app/models/wbw_text.rb, app/views/community/docs.html.erb, app/views/community/tools.html.erb, app/views/docs/_translation_formats.html.erb, app/views/resources/_featured_cards.html.erb, app/views/resources/_resources_list.html.erb, app/views/resources/index.html.erb, app/views/resources/show.html.erb, app/views/word_text_proofreadings/show.html.erb, config/routes.rb, db/migrate/20240909172906_create_tajweed_words.rb, db/migrate/20241007092406_add_dk_v1_script.rb, db/schema.rb
=> Resource help

app/models/quran_api_record.rb, app/models/word.rb, app/views/word_text_proofreadings/show.html.erb
This PR add word images to Quran script proofreading tool
=> add word images

README.md
I tried running the command 
```bash
psql quran_dev < "path to sql dump file"
```
but it didn't work so I tried another way and it worked, so I thought about sharing it. I will add other tips that helped me in running the project successfully.
PS: I'm running the project on M1 Pro.
=> a new command added to restore the database from sql dumb.

.gitignore, app/controllers/surah_audio_files_controller.rb, app/javascript/segments/components/ActionBar.vue, app/javascript/segments/components/SelectAudioSrc.vue, app/javascript/segments/components/Verse.vue, app/javascript/segments/store/index.js, app/views/ayah_audio_files/segments.json.jbuilder
We can now pats raw segments data and compare the highlighting results
=> Add segment highlighting comparison with raw segments

app/admin/audio/recitation.rb, app/jobs/export/ayah_recitation_segments_job.rb, app/models/contact_message.rb, app/models/draft/tafsir.rb, app/models/draft/translation.rb, app/models/morphology/matching_verse.rb, app/models/morphology/phrase.rb, app/models/morphology/phrase_verse.rb, app/models/raw_data/resource.rb, app/models/recitation.rb, app/models/user.rb, app/models/wbw_text.rb, app/views/admin/_export_ayah_segments_db.html.erb, app/views/morphology_phrases/_ayah.html.erb, app/views/morphology_phrases/_suggestions.html.erb, db/migrate/20241101123851_add_source_to_phrase.rb, db/schema.rb
This PR includes:
- Fixed the table name for audio/segment export
- Includes source for phrases 
- Fixed phrase builder, select words was breaking
=> Improvements 

app/admin/data_source.rb, app/models/data_source.rb, app/models/resource_content.rb, db/migrate/20241114223249_add_resource_count_to_data_source.rb, db/schema.rb
=> Group resources for data sources based on resource type

app/helpers/tool_docs_helper.rb, app/models/word_translation.rb, app/views/community/tool_help.html.erb, app/views/word_translations/_table.html.erb, app/views/word_translations/new.html.erb
=> Word group translation documentation 

app/admin/content/resource_content.rb, app/admin/downloads/downloadable_resource.rb, app/controllers/users/sessions_controller.rb, app/helpers/resources_helper.rb, app/models/downloadable_resource.rb, app/models/resource_content.rb, app/views/card/_download_dropdown.html.erb, app/views/devise/sessions/_form.html.erb, app/views/devise/sessions/new.html.erb, app/views/resources/detail.html.erb, config/routes.rb
Fix download resource link #174
=> Fix resource download

app/admin/quran/mushaf.rb, app/admin/quran/mushaf_page.rb, app/jobs/export/mushaf_layout_export_job.rb, app/models/downloadable_resource.rb, app/models/draft/translation.rb, app/models/mushaf.rb, app/models/mushaf_line_alignment.rb, app/models/mushaf_page.rb, app/views/layouts/mailer.html.erb, app/views/shared/_mushaf_page.html.erb, config/sidekiq.yml, db/migrate/20230720192356_create_mushaf_line_alignments.rb, db/migrate/20241227164608_add_lines_count_to_mushaf_page.rb, db/schema.rb, lib/export_mushaf_layout.rb, lib/exporter/downloadable_resources.rb, lib/importer/quran_enc.rb, lib/tasks/one_time.rake, lib/text/formatter.rb
This PR:
- Add lines count column to mushaf page 
- Add validation to exported mushaf layout data and alert about issues
=> Mushaf lines

app/models/downloadable_resource.rb, app/models/resource_content.rb, app/views/resources/_preview.html.erb, app/views/resources/detail.html.erb, app/views/resources/previews/_mushaf_layout.html.erb, app/views/resources/previews/_quran_script.html.erb, app/views/resources/show.html.erb, app/views/shared/_page_font.html.erb, lib/exporter/base_exporter.rb, lib/exporter/export_ayah_recitation.rb, lib/exporter/export_font.rb, lib/exporter/export_quran_ayah_script.rb, lib/exporter/export_quran_word_script.rb, lib/importer/base.rb, lib/importer/quran_enc.rb, public/compare-audio.html
This PR:
- Add preview for Quran script 
- Export page number for Quran glyph based script
=> improve resource preview

app/admin/audio/audio_recitation.rb, app/jobs/export/split_gapeless_recitation_job.rb, app/views/admin/_split_to_gapped.html.erb, lib/audio/split_gapeless_audio.rb, lib/audio/split_gapeless_segment.rb, public/compare-audio.html
=> Split gapped audio from gapeless

app/admin/content/resource_content.rb, app/admin/draft/word_translation.rb, app/jobs/quran_enc/approve_draft_translation_job.rb, app/models/draft/tafsir.rb, app/models/draft/word_translation.rb, app/models/resource_content.rb, app/models/verse.rb, app/models/word.rb, app/views/tajweed_words/_sidebar.html.erb, db/migrate/20250113120827_create_draft_word_translations.rb, db/schema.rb, lib/layout_exporter/ayah_metadata.rb, lib/layout_exporter/last_word_hash.rb, lib/layout_exporter/page_indices_lookup.rb, lib/layout_exporter/page_lookup.rb
This PR add draft word translation tool
=> Draft word translation

app/controllers/exports_controller.rb, app/views/exports/mushaf.html.erb, app/views/exports/mushaf_page.html.erb, config/routes.rb, scripts/calculate-line-ratio.js
=> Export whole mushaf

app/controllers/word_text_proofreadings_controller.rb, app/views/word_text_proofreadings/compare_words.html.erb, config/routes.rb
tools to compare waqf signs within different scripts
=> Add waqf sign comparison

app/views/arabic_transliterations/index.html.erb, app/views/community/_char_font_options.html.erb, app/views/community/_char_info_form.html.erb, app/views/morphology_phrases/_phrase_list.html.erb, app/views/morphology_phrases/_proofread_list.html.erb, app/views/mushaf_layouts/index.html.erb, app/views/resources/resources_view/_list.html.erb, app/views/shared/_filters.html.erb, app/views/surah_audio_files/index.html.erb, app/views/tafsir_proofreadings/index.html.erb, app/views/tajweed_words/index.html.erb, app/views/translation_proofreadings/index.html.erb
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/cd797c19-ae5a-409c-b409-205f4254d307) | ![image](https://github.com/user-attachments/assets/09728d69-454f-4b9e-b5dd-21654dd56510) |
| ![image](https://github.com/user-attachments/assets/2b884487-27b8-4ba0-aff6-6f49a4a407db) | !![image](https://github.com/user-attachments/assets/9772fc77-6b01-4fa7-82fe-887914264136) |
=> tools pages ui enhanced

app/admin/draft/tafisr.rb, app/components/split_screen_component.html.erb, app/javascript/controllers/for_admin.js, app/jobs/quran_enc/approve_draft_translation_job.rb, app/models/draft/tafsir.rb, app/models/resource_content.rb, app/views/admin/_compare_draft_tafsir_ayah_grouping.html.erb, app/views/admin/_tafisr_compare.html.erb, db/migrate/20250116160316_renmae_properites_to_metadata.rb, db/schema.rb, lib/exporter/downloadable_resources.rb, lib/qul_exported_file_key_generator.rb
- Allow admins to clone or run the text sanitization on tafsir
- Track bulk changes for tafsir
=> Improve draft tafsir

app/helpers/tools_helper.rb
Corrects spelling in documentation
=> Fix tafsir typo

README.md
Salam!
Nothing much, just fixed a typo. :)
=> Fix typo in features list

app/helpers/resources_helper.rb, app/models/audio_file.rb, app/views/resources/show.html.erb
=> Fix duplicate resource card. Close #217

Gemfile, Gemfile.lock, app/admin/settings/analytic_page.rb, app/helpers/analytic_helper.rb, app/javascript/active_admin.js, app/javascript/controllers/event_tracker_controller.js, app/javascript/controllers/for_admin.js, app/javascript/controllers/index.js, app/models/ability.rb, app/models/user.rb, app/views/landing/_header.html.erb, app/views/layouts/application.html.erb, app/views/layouts/devise.html.erb, config/initializers/active_admin.rb, package.json, yarn.lock
=> Update GA id and add basic analytics

app/admin/quran/chapter.rb, app/assets/stylesheets/shared/surah_names.scss, app/helpers/tool_docs_helper.rb, app/models/chapter.rb, app/models/downloadable_resource.rb, db/migrate/20250505205752_add_glyph_codes_to_chapters.rb, db/schema.rb
Closes #233
This PR add surah name font preview to admin. Glyph codes are moved to db now. 
The next step will be to export these fonts.
=> Add surah name font preview

db/migrate/20250506055426_add_root_id_to_words.rb, lib/tasks/migrate_word_roots.rake
Fix: #231
This PR update the Word -> Root schema. Migrate from `many to many` to `one to many` relation.
=> Fix schema for word root

app/admin/topic.rb, lib/tasks/import_arabic_topics.rake
**Task https://github.com/TarteelAI/quranic-universal-library/issues/256**
This PR updates the Topics by adding a new `resource` named `Arabic Topics`. Scrapes Arabic topics from 
`quranpedia.net/topics` and inserts the data into the `Arabic Topics` resource.
=> Create Arabic Topics Resource

lib/tasks/bridges_import.rake
This PR import the draft translation named: `Fadel Soliman, Bridges’ translation`
=> Import draft translation

lib/tasks/import_arabic_topics.rake
Now import `Arabic Topics` without any duplicate names
=> Updated Arabic Topics

Gemfile, Gemfile.lock, app/admin/content/resource_content.rb, app/admin/draft/content.rb, app/models/draft/content.rb, lib/export_quran_fts.rb, lib/tasks/import_subjective_tafsir.rake
=> Export search db

app/admin/draft/tafisr.rb, app/assets/stylesheets/shared/content.scss, app/assets/stylesheets/shared/font_faces.scss, app/models/ayah_theme.rb, app/models/draft/tafsir.rb, app/views/admin/_tafisr_compare.html.erb, app/views/resources/previews/_ayah_theme.html.erb, app/views/resources/previews/_similar_ayah.html.erb, app/views/resources/previews/_tafsir.html.erb, lib/exporter/export_matching_ayah.rb
This PR add documentation for similar ayah and ayah theme resources.
=> Docs for similar ayah and ayah themes

app/models/juz.rb, app/views/resources/_preview.html.erb, app/views/resources/previews/_ayah_theme.html.erb, app/views/resources/previews/_quran_metadata.html.erb, app/views/resources/previews/_tafsir.html.erb, app/views/resources/previews/quran_metadata/_ayah_help.html.erb, app/views/resources/previews/quran_metadata/_ayah_preview.html.erb, app/views/resources/previews/quran_metadata/_hizb_help.html.erb, app/views/resources/previews/quran_metadata/_hizb_preview.html.erb, app/views/resources/previews/quran_metadata/_juz_help.html.erb, app/views/resources/previews/quran_metadata/_juz_preview.html.erb, app/views/resources/previews/quran_metadata/_manzil_help.html.erb, app/views/resources/previews/quran_metadata/_manzil_preview.html.erb, app/views/resources/previews/quran_metadata/_rub_preview.html.erb, app/views/resources/previews/quran_metadata/_ruku_help.html.erb, app/views/resources/previews/quran_metadata/_ruku_preview.html.erb, app/views/resources/previews/quran_metadata/_sajda_help.html.erb, app/views/resources/previews/quran_metadata/_sajda_preview.html.erb, app/views/resources/previews/quran_metadata/_surah_help.html.erb, app/views/resources/previews/quran_metadata/_surah_preview.html.erb, lib/exporter/export_quran_meta_data.rb
=> Add Quran metadata docs

app/admin/draft/translation.rb, app/controllers/surah_audio_files_controller.rb, app/javascript/controllers/ayah_segment_player_controller.js, app/javascript/controllers/segment_player_controller.js, app/models/audio/recitation.rb, app/models/audio/segment.rb, app/models/audio_file.rb, app/models/recitation.rb, app/views/ayah_audio_files/segment_builder.html.erb, app/views/surah_audio_files/segment_builder.html.erb, lib/audio_segment/ayah_by_ayah.rb, lib/audio_segment/surah_by_surah.rb, lib/exporter/export_surah_recitation.rb, lib/tasks/one_time.rake
Fix gapped audio segments format, we used to have 4 values per segment. The first value was just the index counter. 
Gapless audio has three value per segment(word number, start time, end time)
This PR standardise both gapped and gapless segments.
=> Fix segment format

lib/importer/tafsir_app.rb
This PR Updates `Tafsir_app.rb` file to add` wahidi-asbab Recource` to `import wahidi-asbab data` from `TafsirApp`
=> Import wahidi-asbab data

app/controllers/segments/dashboard_controller.rb, docker/qul.tarteel.ai
Allow users to upload zipped segments db, current db size 108mb and zipped size is 38mb. This will save upload time.
=> Allow uploading zipped db

app/controllers/api/v1/audio/recitations_controller.rb, app/presenters/v1/audio/recitation_presenter.rb, app/views/api/v1/audio/recitations/_ayah_recitation.json.props, app/views/api/v1/audio/recitations/_surah_recitation.json.props, app/views/api/v1/audio/recitations/ayah_recitation_detail.json.props, app/views/api/v1/audio/recitations/ayah_recitations.json.props, app/views/api/v1/audio/recitations/surah_recitation_detail.json.props, app/views/api/v1/audio/recitations/surah_recitations.json.props, config/routes.rb
Add surah and ayah recitation API
=> Add recitation api

app/helpers/learning_activity_helper.rb, app/javascript/controllers/activities/word_match_controller.js, app/javascript/controllers/index.js, app/views/learning_activities/_word_match.html.erb
Match Arabic words with their correct English translations by dragging or tapping. Connect the dots between matching pairs and see visual feedback with green checkmarks for correct matches and red crosses for incorrect ones. Complete all pairs to finish the activity!
The feature includes:
- Two-column layout (Arabic words on left, translations on right)
- Drag-and-drop or tap-to-select matching
- Visual connection lines with tick (✓) or cross (✕) indicators
- Progress tracking
- Immediate feedback on correct/incorrect matches
=> Add the [Word Match] activity with functionality on learning activities page.

app/admin/content/resource_content.rb, app/admin/content/root_detail.rb, app/models/draft/content.rb, app/models/resource_content.rb, app/models/root_detail.rb, db/migrate/20250916073555_create_root_details.rb
This PR adds a new `RootDetail` Resource to manage and store data related to root details
=> Root word detail

app/admin/audio/audio_recitation.rb, app/admin/audio/recitation.rb, app/admin/dashboard.rb, app/jobs/audio/export_audio_segments_job.rb, app/jobs/audio/split_gapless_recitation_job.rb, app/jobs/segments/export_reciter_segments_job.rb, app/views/admin/_export_audio_segments_db.html.erb, app/views/segments/dashboard/reciter.html.erb, lib/audio/split_gapless_audio.rb, lib/audio/split_gapless_segment.rb, lib/audio_segment/tarteel.rb, lib/batch_audio_segment_parser.rb, lib/tasks/audio.rake
=> Export gapless segments
